runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/assets/AxoSal.ico
  upload: static/assets/AxoSal\.ico

- url: /static
  static_dir: static

- url: .*  # This regex directs all routes to main.app
  script: main.app
  secure: always
